### ISSUE TITLE
Show quantity of telefrags made by player

### ISSUE THREAD

**Issue by shadbarton** [adobromilskiy/quake3-stats#3]
Optional: Add statistic by player who was telefraged
For example:
twist: telefraged 229 players.
100 - Ignat
100 - Riloshkvar
29 - JavaScripter

**Comment by adobromilskiy** [comment]
Unfortunately, it is impossible. We can only show count of telefrags for whole time.

**Comment by shadbarton** [comment]
Hope this may be able with https://github.com/adobromilskiy/quake3-stats/issues/4

**Comment by adobromilskiy** [comment]
@DIvakh  here is the formula:

telefrags = kills - score - suicides.

**Comment by DIvakh** [comment]
> @DIvakh here is the formula:
> 
> telefrags = kills - score - suicides.

o7 o7 o7

**Comment by shadbarton** [comment]
> @DIvakh here is the formula:
> 
> telefrags = kills - score - suicides.
telefrags = score - kills + suicides.
